<a href="https://colab.research.google.com/github/dohyeon-kim012/python-1./blob/main/5_20_%EC%98%A4%ED%9B%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

n1 = np.random.randint(0, 100, 10)
n1

array([94, 66, 72, 98, 52, 49, 53,  9,  7, 99])

In [ ]:
type(n1) , n1.shape , n1.ndim , n1.size , n1.nbytes , n1.itemsize

(numpy.ndarray, (10,), 1, 10, 80, 8)

In [ ]:
n = n1.copy()
n[:]    # = n[0:10]

array([72, 30,  0, 93, 17, 67, 45, 71, 56, 65])

In [ ]:
n.reshape(2, 5)

array([[72, 30,  0, 93, 17],
       [67, 45, 71, 56, 65]])

In [ ]:
n.sort()
n

array([ 0, 17, 30, 45, 56, 65, 67, 71, 72, 93])

In [ ]:
n.sort(axis=1)    # 1차원이라 axis=1 값은 없음. 에러 남(axis=0만 가능)
n

In [ ]:
n.sort?    # 도움말 보기

In [ ]:
n2 = np.random.randint(1, 100, 12)
n2

array([40, 63, 94, 17, 30, 89, 19, 61, 97, 54, 47, 42])

In [ ]:
n2.reshape(4, 3)

array([[40, 63, 94],
       [17, 30, 89],
       [19, 61, 97],
       [54, 47, 42]])

In [ ]:
n21 = np.arange(1, 17, dtype=np.int16)
n21

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
      dtype=int16)

In [ ]:
n = n21.reshape(4, 4)
n

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int16)

In [ ]:
n[0, 3] , n[0:2, 1:3] , n[1:, 2:] , n[2:, :2] , n[:1, 1:3], n[2:, 1:3]

(4, array([[2, 3],
        [6, 7]], dtype=int16), array([[ 7,  8],
        [11, 12],
        [15, 16]], dtype=int16), array([[ 9, 10],
        [13, 14]], dtype=int16), array([[2, 3]], dtype=int16), array([[10, 11],
        [14, 15]], dtype=int16))

In [ ]:
n[2:4, 1:3] * 3  ,   n[2:4, 1:3] == 0

(array([[30, 33],
        [42, 45]], dtype=int16), array([[False, False],
        [False, False]]))

In [ ]:
n[0] , n[0] < 3

(array([1, 2, 3, 4], dtype=int16), array([ True,  True, False, False]))

In [ ]:
n[0][3] = 44
n

array([[ 1,  2,  3, 44],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int16)

In [ ]:
n[:, -1] = 100
n

array([[  1,   2,   3, 100],
       [  5,   6,   7, 100],
       [  9,  10,  11, 100],
       [ 13,  14,  15, 100]], dtype=int16)

In [ ]:
n.sum() , n[0].sum() , n.max()

(496, 106, 100)

In [ ]:
n.max(axis=0) , n.max(axis=1)

(array([ 13,  14,  15, 100], dtype=int16),
 array([100, 100, 100, 100], dtype=int16))

In [ ]:
n.mean(axis=1)

array([26.5, 29.5, 32.5, 35.5])

In [ ]:
n.std()    # 표준편차 

40.03123780249619

In [ ]:
np.median(n)    # 중앙값

10.5

In [ ]:
np.median(n[:,1])

8.0

In [ ]:
np.zeros(5)  ,  np.ones(5)

(array([0., 0., 0., 0., 0.]), array([1., 1., 1., 1., 1.]))

In [ ]:
np.tri(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.empty(6)

array([4.68949657e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

In [ ]:
np.zeros((2, 6)) , np.zeros((3, 4))

(array([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]), array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [ ]:
n2 = np.array([4, 5, 6, 7], np.int32)
n2, n2.nbytes

(array([4, 5, 6, 7], dtype=int32), 16)

In [ ]:
k = [i for i in range(5, 51, 5)]
k , type(k)

([5, 10, 15, 20, 25, 30, 35, 40, 45, 50], list)

In [ ]:
t = (i for i in range(10, 101, 10))
t, type(t)

(<generator object <genexpr> at 0x7f19d9314e50>, generator)

In [ ]:
n10 = np.array(k)    # list는 array 됨
n10

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
n11 = np.array(t)    # generator는 array 안 됨
n11

array(<generator object <genexpr> at 0x7f19d9314e50>, dtype=object)

In [ ]:
n12 = np.array(k)
n13 = n12.reshape(2, 5)
n13

array([[ 5, 10, 15, 20, 25],
       [30, 35, 40, 45, 50]])

In [ ]:
s1 = pd.Series([2, 4, 6, 8])
type(s1) , s1.shape , s1.ndim , s1.nbytes , s1.items , s1.index   # 0,1,2,3은 인덱스, 2,4,6,8이 값임

(pandas.core.series.Series, (4,), 1, 32, <bound method Series.items of 0    2
 1    4
 2    6
 3    8
 dtype: int64>, RangeIndex(start=0, stop=4, step=1))

In [ ]:
s1.index = [['a)', 'b)', 'c)', 'd)']]
s1

a)    2
b)    4
c)    6
d)    8
dtype: int64

In [ ]:
s1['a)']    #index -> key, 우측 값-> value, key와 value 두 가지 통해서 다 접근 가능

a)    2
dtype: int64

In [ ]:
s1.iloc[1]

4

In [ ]:
s1.loc['b)']

b)    4
dtype: int64

In [ ]:
s1.iloc[1:4]

b)    4
c)    6
d)    8
dtype: int64

In [ ]:
pd1 = pd.read_csv('/content/sample_data/california_housing_test.csv')
type(pd1), pd1.shape

(pandas.core.frame.DataFrame, (3000, 9))

In [ ]:
p = pd1.copy()
p

longitude  latitude  ...  median_income  median_house_value
0       -122.05     37.37  ...         6.6085            344700.0
1       -118.30     34.26  ...         3.5990            176500.0
2       -117.81     33.78  ...         5.7934            270500.0
3       -118.36     33.82  ...         6.1359            330000.0
4       -119.67     36.33  ...         2.9375             81700.0
...         ...       ...  ...            ...                 ...
2995    -119.86     34.42  ...         1.1790            225000.0
2996    -118.14     34.06  ...         3.3906            237200.0
2997    -119.70     36.30  ...         2.2895             62000.0
2998    -117.12     34.10  ...         3.2708            162500.0
2999    -119.63     34.42  ...         8.5608            500001.0

[3000 rows x 9 columns]

In [ ]:
p.head(3)

longitude  latitude  ...  median_income  median_house_value
0    -122.05     37.37  ...         6.6085            344700.0
1    -118.30     34.26  ...         3.5990            176500.0
2    -117.81     33.78  ...         5.7934            270500.0

[3 rows x 9 columns]

In [ ]:
pd2 = pd.read_csv('/content/sample_data/sc.csv' , header=None)
p = pd2.copy()
p

0   1   2   3
0  이순신  85  87  90
1  강감찬  75  80  95
2  한석봉  99  98  99
3  황진이  99  99  99
4  안중근  90  85  90
5  박문수  95  98  96
6  임꺽정  15  35  45
7  김정호  90  95  80
8  정몽주  90  90  95
9  김도도  50  45  60

In [ ]:
p.columns = ['이름', '국어', '영어', '수학']
p

이름  국어  영어  수학
0  이순신  85  87  90
1  강감찬  75  80  95
2  한석봉  99  98  99
3  황진이  99  99  99
4  안중근  90  85  90
5  박문수  95  98  96
6  임꺽정  15  35  45
7  김정호  90  95  80
8  정몽주  90  90  95
9  김도도  50  45  60

In [ ]:
p.shape, type(p) , p.ndim , p.size , p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   이름      10 non-null     object
 1   국어      10 non-null     int64 
 2   영어      10 non-null     int64 
 3   수학      10 non-null     int64 
dtypes: int64(3), object(1)
memory usage: 448.0+ bytes


((10, 4), pandas.core.frame.DataFrame, 2, 40, None)

In [ ]:
p.describe() , p.index , p.columns

(              국어         영어        수학
 count  10.000000  10.000000  10.00000
 mean   78.800000  81.200000  84.90000
 std    26.682495  22.714655  18.29663
 min    15.000000  35.000000  45.00000
 25%    77.500000  81.250000  82.50000
 50%    90.000000  88.500000  92.50000
 75%    93.750000  97.250000  95.75000
 max    99.000000  99.000000  99.00000,
 RangeIndex(start=0, stop=10, step=1),
 Index(['이름', '국어', '영어', '수학'], dtype='object'))

In [ ]:
p['총점'] = p['국어'] + p['영어'] + p['수학']
p.loc[:, ['이름','총점']]   

이름   총점
0  이순신  262
1  강감찬  250
2  한석봉  296
3  황진이  297
4  안중근  265
5  박문수  289
6  임꺽정   95
7  김정호  265
8  정몽주  275
9  김도도  155

In [ ]:
p['평균'] = p['총점'] / 3
p.loc[:,['이름', '총점', '평균']]

이름   총점         평균
0  이순신  262  87.333333
1  강감찬  250  83.333333
2  한석봉  296  98.666667
3  황진이  297  99.000000
4  안중근  265  88.333333
5  박문수  289  96.333333
6  임꺽정   95  31.666667
7  김정호  265  88.333333
8  정몽주  275  91.666667
9  김도도  155  51.666667

In [ ]:
p.loc[:, ['수학']] >= 70    # iloc와 loc 모두 True / False 로 결과 나타남  ( = p.iloc[:, 3] >= 70)

수학
0   True
1   True
2   True
3   True
4   True
5   True
6  False
7   True
8   True
9  False

In [ ]:
p.loc[4:6,['국어','영어']]

국어  영어
4  90  85
5  95  98
6  15  35

In [ ]:
p['수학'] >= 70    #masking (True / False로 값 나타남)

0     True
1     True
2     True
3     True
4     True
5     True
6    False
7     True
8     True
9    False
Name: 수학, dtype: bool

In [ ]:
p.iloc[:, 1:] >= 70    # 합격, 불합격 등 이분법적인 요소 간단하게 나눌 수 있음

국어     영어     수학    총점     평균
0   True   True   True  True   True
1   True   True   True  True   True
2   True   True   True  True   True
3   True   True   True  True   True
4   True   True   True  True   True
5   True   True   True  True   True
6  False  False  False  True  False
7   True   True   True  True   True
8   True   True   True  True   True
9  False  False  False  True  False

In [ ]:
p.iloc[:, 2:4] <= 60

영어     수학
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False
5  False  False
6   True   True
7  False  False
8  False  False
9   True   True

In [ ]:
p5 = p[(p['수학'] >= 70) & (p['수학'] <= 90)]    # 조건에 해당되는 값만 구하기
p5

이름  국어  영어  수학   총점         평균
0  이순신  85  87  90  262  87.333333
4  안중근  90  85  90  265  88.333333
7  김정호  90  95  80  265  88.333333

In [ ]:
p.sum() , p.mean() , p.sum(axis=1)

(이름    이순신강감찬한석봉황진이안중근박문수임꺽정김정호정몽주김도도
 국어                               788
 영어                               812
 수학                               849
 총점                              2449
 평균                           816.333
 dtype: object, 국어     78.800000
 영어     81.200000
 수학     84.900000
 총점    244.900000
 평균     81.633333
 dtype: float64, 0    611.333333
 1    583.333333
 2    690.666667
 3    693.000000
 4    618.333333
 5    674.333333
 6    221.666667
 7    618.333333
 8    641.666667
 9    361.666667
 dtype: float64)

In [ ]:
p['국어'].value_counts()    # 점수분포도 등 확인에 유용

90    3
99    2
95    1
75    1
15    1
85    1
50    1
Name: 국어, dtype: int64

In [ ]:
p['국어'].value_counts(ascending = False)

90    3
99    2
95    1
75    1
15    1
85    1
50    1
Name: 국어, dtype: int64

In [ ]:
p['국어'].sort_values()

6    15
9    50
1    75
0    85
4    90
7    90
8    90
5    95
2    99
3    99
Name: 국어, dtype: int64

In [ ]:
p['국어'].sort_values(ascending=False)

3    99
2    99
5    95
8    90
7    90
4    90
0    85
1    75
9    50
6    15
Name: 국어, dtype: int64

In [ ]:
p.sort_values(by='영어')

이름  국어  영어  수학   총점         평균
6  임꺽정  15  35  45   95  31.666667
9  김도도  50  45  60  155  51.666667
1  강감찬  75  80  95  250  83.333333
4  안중근  90  85  90  265  88.333333
0  이순신  85  87  90  262  87.333333
8  정몽주  90  90  95  275  91.666667
7  김정호  90  95  80  265  88.333333
2  한석봉  99  98  99  296  98.666667
5  박문수  95  98  96  289  96.333333
3  황진이  99  99  99  297  99.000000

In [ ]:
p.sort_values(by=['영어', '수학'], inplace=True)    # inplace=True : 원본 값 자체를 바꿈
p

이름  국어  영어  수학   총점         평균
6  임꺽정  15  35  45   95  31.666667
9  김도도  50  45  60  155  51.666667
1  강감찬  75  80  95  250  83.333333
4  안중근  90  85  90  265  88.333333
0  이순신  85  87  90  262  87.333333
8  정몽주  90  90  95  275  91.666667
7  김정호  90  95  80  265  88.333333
5  박문수  95  98  96  289  96.333333
2  한석봉  99  98  99  296  98.666667
3  황진이  99  99  99  297  99.000000

In [ ]:
p['영어'] + 5

6     40
9     50
1     85
4     90
0     92
8     95
7    100
5    103
2    103
3    104
Name: 영어, dtype: int64

In [ ]:
def get_grade(x):
    grade = ''
    if x >= 90: grade = '수'
    elif x >= 80: grade = '우'
    elif x >= 70: grade = '미'
    elif x >= 60: grade = '양'
    else: grade = '가'
    return grade
p['평가'] = p['평균'].apply(lambda x: get_grade(x))

In [ ]:
p

이름  국어  영어  수학   총점         평균 평가
6  임꺽정  15  35  45   95  31.666667  가
9  김도도  50  45  60  155  51.666667  가
1  강감찬  75  80  95  250  83.333333  우
4  안중근  90  85  90  265  88.333333  우
0  이순신  85  87  90  262  87.333333  우
8  정몽주  90  90  95  275  91.666667  수
7  김정호  90  95  80  265  88.333333  우
5  박문수  95  98  96  289  96.333333  수
2  한석봉  99  98  99  296  98.666667  수
3  황진이  99  99  99  297  99.000000  수