<a href="https://colab.research.google.com/github/dohyeon-kim012/python-1./blob/main/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%20%ED%81%90%EB%A0%88%EC%9D%B4%ED%84%B0%202%EC%B0%A8/01.numpy%20%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [1]:
import numpy as np   # 수치 연산을 위한 python 라이브러리

##np.full , np.zeros

np.zeros -> 딥러닝이나 머신러닝에서 편형(bias) 초기값 으로 많이 사용됨

In [2]:
# 5로 채워진 배열 만들기 (np.zeros(()) / np.ones(()) )

np.full((2, 3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

## 점구간 만들기
* np.linspace
* 시각화에서 선을 그을 용도로 많이 사용됨

In [3]:
np.linspace(1, 10, 3)    # 1부터 10까지 3개의 수를 균일한 구간으로 만들기 -> 2개의 구간 생성됨

array([ 1. ,  5.5, 10. ])

In [4]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

## Random
* 랜덤 배열은 **딥러닝**에서 매개변수(가중치 W, 편향 b)를 초기화 하기 위해서 사용
* 초기화 : 최초에 가지고 있는 값

* 생성자 : 객체 초기화 메소드
   -> 클래스를 이용해서 객체를 만들 때 객체가 처음 가지고 있어야 하는 값을 세팅하는 method 

### 정규분포 랜덤
* np.random.randn 
* 50%가 되는 값. median = mean

In [5]:
np.random.randn(16)

array([-1.21309927, -0.72940403,  0.5214376 ,  0.58177329, -1.21813821,
       -1.54823738,  0.4732756 , -0.32339391, -1.7621498 ,  1.02486764,
        2.12345415, -0.9179002 ,  1.50985159, -0.77248176,  0.58085554,
        0.15810916])

In [6]:
np.random.randn(2, 3, 4)

array([[[-0.243581  ,  0.25890425,  0.20845216, -1.19891754],
        [-0.29978936, -0.1576376 ,  0.33960409,  0.13943463],
        [-0.98519904,  0.05884357, -1.95372209,  0.34998452]],

       [[-1.35038106, -0.07736338,  0.15768942,  0.85674765],
        [-0.95762569, -0.22873304, -0.8818412 , -0.30229291],
        [-1.90895539,  0.61008933, -1.31867416, -1.68926981]]])

### 균등분포 랜덤
* np.random.uniform

In [7]:
np.random.uniform(1.0, 3.0, size=(3, 4))

array([[2.58500618, 2.6282424 , 1.54106434, 1.70235019],
       [1.58857808, 1.55997623, 2.00340921, 2.67598983],
       [1.99283167, 1.63837995, 2.94281096, 2.60171301]])

### 정수 랜덤 샘플링
* np.random.choice
* 샘플링 : 전체(모분포)에서 일부(표본)를 추출하는 행위
* 방대한 양의 데이터를 다룰 때, 모분포를 파악할 수가 없으니 일부만 추출해서 데이터를 사용하기 위함
* 딥러닝에서 mini-batch를 만들 때 사용됨

In [8]:
np.random.choice(10, size=(2, 3))  # 0 ~ 9 까지의 정수를 랜덤하게 (2, 3) 배열 형태로 추출 -> 중복 추출이 기본값임

array([[3, 1, 3],
       [1, 2, 5]])

In [9]:
# 배열 내에서도 랜덤 추출 가능
arr = np.arange(1, 6)

np.random.choice(arr, size=(2, 2))   # -> 중복 추출이 되기 때문에 size=(2, 3) 도 가능함

array([[1, 4],
       [1, 1]])

In [10]:
# 중복 추출 X -> replace 옵션 넣으면 중복 추출 안 됨
np.random.choice(arr, size=(2, 2), replace=False)

array([[4, 2],
       [5, 3]])

## 랜덤 정수 배열 만들기
* np.random.randint

In [12]:
arr1 = np.random.randint(1, 100, size=(5, ))
arr1

array([95, 64, 19,  6, 72])

In [13]:
arr2 = np.random.randint(1, 100, size=(5, 1))
arr2

array([[23],
       [14],
       [22],
       [49],
       [74]])

## 다차원 배열
* 스칼라 scalar
    * 어떤 실수값 $x$라고 정의
    '''python
    height = 180.1
    age = 34.3
    '''
    * height, age 가 스칼라 
    * 0차원 데이터
* 벡터 vector
    * 실수값 &x&가 모여져 있는 것
    '''python
    heights = [180.1, 175, 165.4]
    '''
    * heights 라는 벡터를 생성
    * scalar를 모은 것
    * 1차원 배열
    * 모아진 데이터의 개수가 N개라면 **N차원 벡터** 라고 함
    * 열벡터를 기본으로 함 (값들을 세로 방향-열로 정렬함)

In [14]:
# 행벡터의 모양을 하고 있지만, 1차원 배열이기 때문에 열벡터로 생각해야 함
heights_1 = np.array([180.1, 175, 165.4])
heights_1

array([180.1, 175. , 165.4])

In [16]:
# 2차원 배열 이지만 이것도 같은 열벡터임
heights_2 = np.array([[180.1], 
                     [175], 
                     [165.4]])
heights_2

array([[180.1],
       [175. ],
       [165.4]])

## 행렬 matrix
* = 2차원 배열
* 1차원 배열인 벡터가 여러 개 모여있는 것
    '''python 
    
    
    person_info = [[180.1, 33, 80.5], 
                 [175.1, 3, 77.3]] 
    '''


## 텐서 tensor
* 3차원 이상의 배열
* 3차원 배열(3차원 텐서)는 2차원 배열이 모여있는 것
* 4차원 텐서는 3차원 배열이 모여있음
* N차원 배열을 텐서라고 함
* 텐서의 개념을 활용해 모든 배열의 모양 이야기 할 수 있음
    * 0 Rank Tensor 스칼라
    * 1 Rank Tensor 벡터
    * 2 Rank Tensor 행렬
    * 3 Rank Tensor 3랭크 텐서 ...


### Tensorflow
* 구글에서 제공하는 딥러닝 프레임워크
* Tensor을 흘린다(flow)
* 흘릴 네터워크를 미리 준비하고 거기에 배열(데이터)를 흘린다

# axis
axis = 축 (데이터가 추가되는 방향의 **인덱스**)
* 3차원 배열에 추가되는건 2차원 배열  -> axis=0
* 2차원 배열에 추가되는건 1차원 배열  -> axis=1
* 1차원 배열에 추가되는건 0차원 스칼라  -> axis=2

In [25]:
arr3 = np.random.randint(1, 37, (size=(3, 4, 3))
arr3

SyntaxError: ignored

In [19]:
np.max(arr3, axis=0)

array([[25, 26, 27],
       [28, 29, 30],
       [31, 32, 33],
       [34, 35, 36]])

In [20]:
np.max(arr3, axis=1)

array([[10, 11, 12],
       [22, 23, 24],
       [34, 35, 36]])

In [21]:
np.max(arr3, axis=2)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

### spread 연산자

In [27]:
arr4 = np.arange(36).reshape(2, 3, 3, 2)
arr4

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]],


       [[[18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29]],

        [[30, 31],
         [32, 33],
         [34, 35]]]])

In [33]:
arr4[0, :, :, 0]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [34]:
arr4[0, ..., 0]  # spread 연산자

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

## 차원 추가 (차원수 확장)
* 흑백 이미지의 형상 (28, 28) 인데
* 딥러닝에서 이미지를 다룰 때는 (N, H, W, C) 를 유지해야한다
* 따라서 (28, 28) -> (1, 28, 28, 1) 로 만들어야 이미지 분석(CNN)을 할 수 있다
* 원하는 차원 위치에 'np.newaxis' 를 추가하면 된다
    * numpy : np.newaxis
    * tensorflow : tf.newaxis

In [ ]:
temp_arr = arr[np.newaxis, ..., np.newaxis]
temp_arr.shape

## 차원 쥐어 짜기
* np.squeeze
* 개수가 1인 차원의 내용을 없애는 기법

In [ ]:
temp_squeeze = np.squeeze(temp_arr)
temp_squeeze.shape

## 평탄화 ★★★★★
* 2차원 이상의 배열을 1차원 배열로 평평하게 펴주는 것 
    * ravel : 원본 배열을 평탄화 시킨 **참조** 배열을 만들어 냄 
     (View 또는 Reference라고 함)
    * flatten : 원본 배열을 평탄화 시킨 **복사된** 배열을 만들어 냄

ravel은 원본과 주소값을 공유하기 때문에 원본 배열에 수정이 가해질 가능성 있고, flatten은 원본 배열에 영향 X

In [36]:
x = np.random.randint(15, size=(3, 5))
x

array([[11, 13,  3,  6,  2],
       [ 2,  7, 11,  5,  5],
       [ 0, 13, 14,  5,  9]])

In [37]:
# ravel  (3, 5 구조인 x를 1차원 배열로 펴기)
temp = np.ravel(x)
temp.shape

(15,)

In [38]:
temp

array([11, 13,  3,  6,  2,  2,  7, 11,  5,  5,  0, 13, 14,  5,  9])

In [39]:
temp[0] = 100
temp

array([100,  13,   3,   6,   2,   2,   7,  11,   5,   5,   0,  13,  14,
         5,   9])

In [40]:
x  # temp만 바꿨는데 원본인 x 값도 변경됨

array([[100,  13,   3,   6,   2],
       [  2,   7,  11,   5,   5],
       [  0,  13,  14,   5,   9]])

In [41]:
## flatten

x = np.random.randint(15, size=(3, 5))
x.shape

(3, 5)

In [42]:
temp_flatten = np.flatten(x)
temp

AttributeError: ignored

In [43]:
temp_flatten[0] = 100
temp_flatten

NameError: ignored

In [44]:
x

array([[ 9, 10,  6,  7, 12],
       [ 6,  8, 10,  3,  7],
       [ 5, 12,  5,  4, 10]])

## reshape (-1)
* 스칼라 원소의 개수가 reshape 함수 내의 모은 숫자를 곱했을 때와 같아야 함
* reshape에서의 -1은 조커 (정확한 수를 몰라도 어디든 넣을 수 있음)

In [45]:
x = np.arange(20)
x  

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [46]:
x.reshape(2, -1, 2)  # -1 에 자동으로 5 값이 대입됨

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [48]:
x.reshape(2, -1, -1)   # -1 을 두 개 넣을 수는 없음

ValueError: ignored

In [51]:
arr = np.random.randn(60000, 28, 28, 3)
arr.shape 

(60000, 28, 28, 3)

In [52]:
arr1 = arr.reshape(60000, -1, 3)
arr1.shape  # 원하는 값만 -1 넣을 수도 있음

(60000, 784, 3)

In [54]:
# 코드 리펙터링 (고급화)
IMAGE_SIZE = arr.shape[0]
IMAGE_CH   = arr.shape[-1]

arr.reshape(IMAGE_SIZE, -1, IMAGE_CH).shape

(60000, 784, 3)

## 브로드 캐스팅
* 차원수가 다른 배열끼리 연산 됨
* 차원이 달라도 0차원 스칼라의 개수가 같으면 연산이 가능
* 저차원 배열을 고차원 배열로 확장
    * 수학적으로 따지게 되면 고차원 배열의 shape와 똑같이 생긴 1벡터(np.ones)를 만들어 저차원 배열과 곱한 배열을 만들어서 계산

In [55]:
x = np.arange(20).reshape(4, 5)
y = np.arange(20, 40).reshape(4, 5)
x + y

array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

브로드 캐스팅은 저차원을 고차원으로 임시로 늘려줌

In [56]:
x + 2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21]])

shape이 다를 때의 연산

In [57]:
a = np.arange(12).reshape(4, 3)     # (4, 3)
b = np.arange(100, 103)             # ( , 3)
c = np.arange(1000, 1004)           # ( , 4)
d = b.reshape(1, 3)                 # (1, 3)
e = np.arange(0, 4).reshape(4, 1)   # (4, 1)

In [58]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

## 전치행렬
* 행렬 $A$의 행과 열의 인덱스를 바꾼 것
* A(i,j)의 인덱스 위치를 A(j,i)로 바꿈 **(따라서 1차원 배열은 안 됨)**
* = Transpose

In [59]:
A = np.arange(6).reshape(2, 3)
A

array([[0, 1, 2],
       [3, 4, 5]])

In [60]:
# ndarray에서 .T만 사용하면 전치행렬이 만들어짐
A.T

array([[0, 3],
       [1, 4],
       [2, 5]])